name: Build and Deploy to GitHub Pages

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      artifact-path: ${{ steps.upload.outputs.artifact-path }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          # plugin-react requires Node >= 20.19.0 (or >=22.12.0)
          node-version: '20.19.0'

      - name: Install dependencies
        # use npm install when no package-lock.json is present on the runner
        run: npm install --no-audit --prefer-offline

      - name: Build
        env:
          BASE_PATH: '/guitar-chords/'
        run: npm run build

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        id: upload
        with:
          name: pages-dist
          path: ./dist

  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: pages-dist

      - name: Deploy to GitHub Pages (gh-pages branch)
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          # deploy the artifact directory created by download-artifact
          folder: pages-dist
          clean: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
